import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import cert from '../assets/cert.png'
import Link from 'next/link'
import axios from 'axios'
import { useAccount } from 'wagmi'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row w-creen h-screen bg-white' >
        <div className='flex flex-col w-1/2 h-screen bg-white justify-center ml-[10%]'>
          <p className='text-[4vmax] font-bold text-gray-800'>Tokenize your Certificates</p>
          <p className='text-[1.5vmax] font-thin text-gray-800'>With Cernft protect authenticity of every certificate you get</p>
          <Link href='./Dashboard' ><button className='bg-purple-800 w-fit h-fit px-4 py-2 rounded-xl text-1xl mt-7' >Get Started</button></Link>
        </div>
        <div className='flex flex-col w-1/2 h-screen bg-white items-center justify-center'>
          <Image src={cert} width={500}/>
        </div>
      </div>
    </>
  )
}
